"""
ITR Authenticity Evidence Scoring Engine.

This module combines independent authenticity signals into one
explainable risk assessment.

Important:

    A clean PDF is NOT automatically genuine.

    A suspicious PDF is NOT automatically fraudulent.

    Authoritative verification has higher priority than heuristic
    evidence.

Architecture:

    PDF Integrity
          |
          v
    Financial Consistency
          |
          v
    Identity / Cross Document
          |
          v
    Metadata / Submission Reuse
          |
          v
    Authenticity Scoring
          |
          +--> risk score
          +--> risk level
          +--> decision
          +--> confidence
          +--> explainable reason
          +--> explainable signals

The scoring engine is intentionally independent of the extraction
layer and API layer.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


# ============================================================
# ENUMS
# ============================================================


class AuthenticityRiskLevel(str, Enum):
    """
    Overall authenticity risk.
    """

    NONE = "none"

    LOW = "low"

    MEDIUM = "medium"

    HIGH = "high"

    CRITICAL = "critical"


class AuthenticityDecision(str, Enum):
    """
    Final evidence-based decision.

    VERIFIED
        Authoritative verification succeeded.

    LIKELY_AUTHENTIC
        No meaningful anomaly was detected.

        This state is retained for compatibility, but the public
        analyze() flow deliberately converts heuristic-only clean
        documents to UNVERIFIED.

    MANUAL_REVIEW
        Evidence is insufficient or contradictory.

    HIGH_RISK
        Strong authenticity anomalies exist.

    REJECT
        Critical evidence indicates that the document should not
        be accepted automatically.

    UNVERIFIED
        There is insufficient evidence to establish authenticity.
    """

    VERIFIED = "verified"

    LIKELY_AUTHENTIC = "likely_authentic"

    MANUAL_REVIEW = "manual_review"

    HIGH_RISK = "high_risk"

    REJECT = "reject"

    UNVERIFIED = "unverified"


class EvidenceSeverity(str, Enum):
    """
    Severity of one authenticity signal.
    """

    INFO = "info"

    LOW = "low"

    MEDIUM = "medium"

    HIGH = "high"

    CRITICAL = "critical"


# ============================================================
# INPUT MODELS
# ============================================================


@dataclass(frozen=True)
class EvidenceSignal:
    """
    One evidence signal produced by an authenticity subsystem.

    rule_id
        Stable identifier for the rule.

    category
        Logical category of the signal.

    severity
        Severity assigned by the producing rule.

    message
        Human-readable description of WHAT was detected.

    reason
        Human-readable explanation of WHY it matters.

    score
        Numeric contribution between 0 and 100.

    evidence
        Machine-readable supporting information.
    """

    rule_id: str

    category: str

    severity: EvidenceSeverity

    message: str

    reason: str

    score: float = 0.0

    evidence: dict[str, Any] = field(
        default_factory=dict
    )


@dataclass(frozen=True)
class AuthenticityEvidenceInput:
    """
    Input to the authenticity scoring engine.

    Each subsystem can contribute independently.

    authoritative_verified
        True only when an actual trusted external source
        confirms the submitted document.

    authoritative_failed
        True when an authoritative source explicitly says
        the submitted document/details do not match.

    cross_document_critical
        Used for situations such as:

            Vedant reference
                  +
            Shashikant submitted
                  +
            reused submission metadata
                  +
            conflicting identity

        Such a combination is treated as critical.

    cross_document_match
        Indicates that reference comparison found shared
        submission-level evidence.

    cross_document_reason
        Human-readable explanation generated by the reference
        comparison layer.

    reference_document_id
        Identifier of the reference document involved in the
        comparison.
    """

    signals: tuple[
        EvidenceSignal,
        ...
    ] = ()

    authoritative_verified: bool = False

    authoritative_failed: bool = False

    cross_document_critical: bool = False

    cross_document_match: bool = False

    cross_document_reason: str = ""

    reference_document_id: str | None = None


# ============================================================
# OUTPUT MODEL
# ============================================================


@dataclass(frozen=True)
class AuthenticityScoringResult:
    """
    Final authenticity scoring result.
    """

    status: str

    decision: AuthenticityDecision

    risk_level: AuthenticityRiskLevel

    risk_score: float

    confidence: float

    verified: bool

    evidence_count: int

    critical_count: int

    high_count: int

    medium_count: int

    low_count: int

    signals: tuple[
        EvidenceSignal,
        ...
    ]

    reason: str

    summary: str

    def to_dict(
        self,
    ) -> dict[str, Any]:
        """
        Serialize result for API response.
        """

        return {
            "status": self.status,

            "decision": (
                self.decision.value
            ),

            "risk_level": (
                self.risk_level.value
            ),

            "risk_score": self.risk_score,

            "confidence": self.confidence,

            "verified": self.verified,

            "evidence_count": self.evidence_count,

            "critical_count": self.critical_count,

            "high_count": self.high_count,

            "medium_count": self.medium_count,

            "low_count": self.low_count,

            "signals": [
                {
                    "rule_id": signal.rule_id,

                    "category": signal.category,

                    "severity": (
                        signal.severity.value
                    ),

                    "message": signal.message,

                    "reason": signal.reason,

                    "score": signal.score,

                    "evidence": dict(
                        signal.evidence
                    ),
                }

                for signal in self.signals
            ],

            "reason": self.reason,

            "summary": self.summary,
        }


# ============================================================
# ENGINE
# ============================================================


class AuthenticityScoringEngine:
    """
    Combine authenticity evidence into one explainable result.

    The engine does not itself extract fields from a PDF.

    Instead, specialized subsystems produce EvidenceSignal
    instances and this engine combines them.

    This separation is important for production because:

        extraction != validation != authenticity
    """

    # ========================================================
    # PUBLIC API
    # ========================================================

    def analyze(
        self,
        evidence: AuthenticityEvidenceInput,
    ) -> AuthenticityScoringResult:
        """
        Analyze authenticity evidence.

        Priority:

            1. Authoritative verification success
            2. Authoritative verification failure
            3. Critical cross-document evidence
            4. Critical signals
            5. Risk scoring
            6. Clean-document unverified state
        """

        signals = tuple(
            evidence.signals
        )

        # ----------------------------------------------------
        # AUTHORITATIVE SOURCE HAS ABSOLUTE PRIORITY
        # ----------------------------------------------------

        if evidence.authoritative_verified:
            return self._authoritatively_verified(
                signals
            )

        if evidence.authoritative_failed:
            return self._authoritatively_failed(
                signals
            )

        # ----------------------------------------------------
        # COUNT SEVERITIES
        # ----------------------------------------------------

        critical_count = sum(
            signal.severity
            == EvidenceSeverity.CRITICAL
            for signal in signals
        )

        high_count = sum(
            signal.severity
            == EvidenceSeverity.HIGH
            for signal in signals
        )

        medium_count = sum(
            signal.severity
            == EvidenceSeverity.MEDIUM
            for signal in signals
        )

        low_count = sum(
            signal.severity
            == EvidenceSeverity.LOW
            for signal in signals
        )

        # ----------------------------------------------------
        # CRITICAL CROSS-DOCUMENT REUSE
        # ----------------------------------------------------

        if (
            evidence.cross_document_critical
            or critical_count > 0
        ):
            return self._critical_result(
                signals,
                cross_document_reason=(
                    evidence.cross_document_reason
                ),
                reference_document_id=(
                    evidence.reference_document_id
                ),
            )

        # ----------------------------------------------------
        # RISK SCORE
        # ----------------------------------------------------

        risk_score = self._calculate_risk(
            signals
        )

        # ----------------------------------------------------
        # RISK LEVEL
        # ----------------------------------------------------

        risk_level = self._risk_level(
            signals,
            risk_score,
        )

        # ----------------------------------------------------
        # DECISION
        # ----------------------------------------------------

        decision = self._decision(
            risk_level
        )

        # ----------------------------------------------------
        # REASON
        # ----------------------------------------------------

        reason = self._reason(
            signals,
            decision,
        )

        # ----------------------------------------------------
        # SUMMARY
        # ----------------------------------------------------

        summary = self._summary(
            decision
        )

        # ----------------------------------------------------
        # CONFIDENCE
        # ----------------------------------------------------

        confidence = self._confidence(
            signals,
            risk_level,
            decision,
        )

        # ----------------------------------------------------
        # IMPORTANT
        #
        # No authoritative source means:
        #
        # clean != verified
        # ----------------------------------------------------

        verified = False

        if not signals:

            decision = (
                AuthenticityDecision.UNVERIFIED
            )

            risk_level = (
                AuthenticityRiskLevel.LOW
            )

            risk_score = 0.0

            reason = (
                "UNVERIFIED: No significant "
                "authenticity anomaly was detected, "
                "but no authoritative source was "
                "available to prove that the "
                "submitted ITR is genuine."
            )

            summary = (
                "Document is technically clean but "
                "remains unverified."
            )

            confidence = 0.55

        elif decision == (
            AuthenticityDecision.LIKELY_AUTHENTIC
        ):

            # Never claim authenticity from heuristics alone.
            decision = (
                AuthenticityDecision.UNVERIFIED
            )

            reason = (
                "UNVERIFIED: No significant "
                "authenticity anomaly was detected, "
                "but the document could not be "
                "independently verified against an "
                "authoritative source."
            )

            summary = (
                "Document is technically clean but "
                "remains unverified."
            )

        return AuthenticityScoringResult(
            status=(
                "unverified"
                if not verified
                else "verified"
            ),

            decision=decision,

            risk_level=risk_level,

            risk_score=risk_score,

            confidence=confidence,

            verified=verified,

            evidence_count=len(
                signals
            ),

            critical_count=critical_count,

            high_count=high_count,

            medium_count=medium_count,

            low_count=low_count,

            signals=signals,

            reason=reason,

            summary=summary,
        )

    # ========================================================
    # AUTHORITATIVE VERIFIED
    # ========================================================

    @staticmethod
    def _authoritatively_verified(
        signals: tuple[
            EvidenceSignal,
            ...
        ],
    ) -> AuthenticityScoringResult:
        """
        Handle successful authoritative verification.
        """

        return AuthenticityScoringResult(
            status="verified",

            decision=(
                AuthenticityDecision.VERIFIED
            ),

            risk_level=(
                AuthenticityRiskLevel.NONE
            ),

            risk_score=0.0,

            confidence=0.99,

            verified=True,

            evidence_count=len(
                signals
            ),

            critical_count=sum(
                signal.severity
                == EvidenceSeverity.CRITICAL
                for signal in signals
            ),

            high_count=sum(
                signal.severity
                == EvidenceSeverity.HIGH
                for signal in signals
            ),

            medium_count=sum(
                signal.severity
                == EvidenceSeverity.MEDIUM
                for signal in signals
            ),

            low_count=sum(
                signal.severity
                == EvidenceSeverity.LOW
                for signal in signals
            ),

            signals=signals,

            reason=(
                "The submitted ITR was confirmed "
                "by an authoritative verification "
                "source."
            ),

            summary=(
                "ITR authenticity was externally "
                "verified."
            ),
        )

    # ========================================================
    # AUTHORITATIVE FAILED
    # ========================================================

    @staticmethod
    def _authoritatively_failed(
        signals: tuple[
            EvidenceSignal,
            ...
        ],
    ) -> AuthenticityScoringResult:
        """
        Handle an explicit authoritative verification failure.
        """

        return AuthenticityScoringResult(
            status="high_risk",

            decision=(
                AuthenticityDecision.REJECT
            ),

            risk_level=(
                AuthenticityRiskLevel.CRITICAL
            ),

            risk_score=1.0,

            confidence=0.99,

            verified=False,

            evidence_count=len(
                signals
            ),

            critical_count=sum(
                signal.severity
                == EvidenceSeverity.CRITICAL
                for signal in signals
            ),

            high_count=sum(
                signal.severity
                == EvidenceSeverity.HIGH
                for signal in signals
            ),

            medium_count=sum(
                signal.severity
                == EvidenceSeverity.MEDIUM
                for signal in signals
            ),

            low_count=sum(
                signal.severity
                == EvidenceSeverity.LOW
                for signal in signals
            ),

            signals=signals,

            reason=(
                "Authoritative verification failed: "
                "the submitted ITR could not be "
                "confirmed by the authoritative "
                "verification source."
            ),

            summary=(
                "Authoritative verification failed."
            ),
        )

    # ========================================================
    # CRITICAL
    # ========================================================

    @staticmethod
    def _critical_result(
        signals: tuple[
            EvidenceSignal,
            ...
        ],
        cross_document_reason: str = "",
        reference_document_id: str | None = None,
    ) -> AuthenticityScoringResult:
        """
        Handle critical authenticity evidence.

        Critical evidence always produces:

            decision = reject
            risk_level = critical
            verified = false
        """

        critical_count = sum(
            signal.severity
            == EvidenceSeverity.CRITICAL
            for signal in signals
        )

        high_count = sum(
            signal.severity
            == EvidenceSeverity.HIGH
            for signal in signals
        )

        medium_count = sum(
            signal.severity
            == EvidenceSeverity.MEDIUM
            for signal in signals
        )

        low_count = sum(
            signal.severity
            == EvidenceSeverity.LOW
            for signal in signals
        )

        # ----------------------------------------------------
        # SELECT PRIMARY EVIDENCE
        # ----------------------------------------------------

        primary = (
            max(
                signals,
                key=lambda signal: (
                    AuthenticityScoringEngine
                    ._severity_rank(
                        signal.severity
                    ),

                    signal.score,
                ),
            )
            if signals
            else None
        )

        # ----------------------------------------------------
        # BUILD EXPLAINABLE REASON
        # ----------------------------------------------------

        if cross_document_reason:
            reason = cross_document_reason

            if reference_document_id:
                reason = (
                    f"{reason} "
                    f"Reference document: "
                    f"{reference_document_id}."
                )

        elif primary and primary.reason:
            reason = primary.reason

        elif primary:
            reason = primary.message

        else:
            reason = (
                "Critical authenticity evidence "
                "was detected."
            )

        # ----------------------------------------------------
        # CRITICAL RESULT
        # ----------------------------------------------------

        return AuthenticityScoringResult(
            status="high_risk",

            decision=(
                AuthenticityDecision.REJECT
            ),

            risk_level=(
                AuthenticityRiskLevel.CRITICAL
            ),

            risk_score=1.0,

            confidence=0.98,

            verified=False,

            evidence_count=len(
                signals
            ),

            critical_count=critical_count,

            high_count=high_count,

            medium_count=medium_count,

            low_count=low_count,

            signals=signals,

            reason=reason,

            summary=(
                "Critical authenticity evidence "
                "was detected. Automatic acceptance "
                "is not permitted."
            ),
        )

    # ========================================================
    # RISK SCORE
    # ========================================================

    @staticmethod
    def _calculate_risk(
        signals: tuple[
            EvidenceSignal,
            ...
        ],
    ) -> float:
        """
        Calculate a bounded risk score.

        The strongest signal receives full weight.

        Additional signals contribute 35% each.

        Final result is bounded between 0 and 1.
        """

        if not signals:
            return 0.0

        scores = sorted(
            (
                max(
                    0.0,
                    min(
                        100.0,
                        float(
                            signal.score
                        ),
                    ),
                )

                for signal in signals
            ),

            reverse=True,
        )

        score = (
            scores[0]
            + sum(
                value * 0.35
                for value in scores[1:]
            )
        )

        return round(
            min(
                1.0,
                score / 100.0,
            ),
            4,
        )

    # ========================================================
    # RISK LEVEL
    # ========================================================

    @staticmethod
    def _risk_level(
        signals: tuple[
            EvidenceSignal,
            ...
        ],
        risk_score: float,
    ) -> AuthenticityRiskLevel:
        """
        Determine overall risk level.

        Explicit severity always takes precedence over
        numeric score.
        """

        severities = [
            signal.severity
            for signal in signals
        ]

        if (
            EvidenceSeverity.CRITICAL
            in severities
        ):
            return (
                AuthenticityRiskLevel.CRITICAL
            )

        if (
            EvidenceSeverity.HIGH
            in severities
        ):
            return (
                AuthenticityRiskLevel.HIGH
            )

        if (
            EvidenceSeverity.MEDIUM
            in severities
        ):
            return (
                AuthenticityRiskLevel.MEDIUM
            )

        if (
            EvidenceSeverity.LOW
            in severities
        ):
            return (
                AuthenticityRiskLevel.LOW
            )

        # ----------------------------------------------------
        # SCORE-BASED FALLBACK
        # ----------------------------------------------------

        if risk_score >= 0.75:
            return (
                AuthenticityRiskLevel.CRITICAL
            )

        if risk_score >= 0.50:
            return (
                AuthenticityRiskLevel.HIGH
            )

        if risk_score >= 0.25:
            return (
                AuthenticityRiskLevel.MEDIUM
            )

        if risk_score > 0:
            return (
                AuthenticityRiskLevel.LOW
            )

        return (
            AuthenticityRiskLevel.NONE
        )

    # ========================================================
    # DECISION
    # ========================================================

    @staticmethod
    def _decision(
        risk_level: AuthenticityRiskLevel,
    ) -> AuthenticityDecision:
        """
        Convert risk level into an authenticity decision.
        """

        if (
            risk_level
            == AuthenticityRiskLevel.CRITICAL
        ):
            return (
                AuthenticityDecision.REJECT
            )

        if (
            risk_level
            == AuthenticityRiskLevel.HIGH
        ):
            return (
                AuthenticityDecision.HIGH_RISK
            )

        if (
            risk_level
            == AuthenticityRiskLevel.MEDIUM
        ):
            return (
                AuthenticityDecision.MANUAL_REVIEW
            )

        if (
            risk_level
            == AuthenticityRiskLevel.LOW
        ):
            return (
                AuthenticityDecision.UNVERIFIED
            )

        return (
            AuthenticityDecision.LIKELY_AUTHENTIC
        )

    # ========================================================
    # REASON
    # ========================================================

    @staticmethod
    def _reason(
        signals: tuple[
            EvidenceSignal,
            ...
        ],
        decision: AuthenticityDecision,
    ) -> str:
        """
        Select the strongest explainable reason.
        """

        if not signals:
            return (
                "UNVERIFIED: No significant "
                "authenticity anomalies were detected, "
                "but no authoritative source was "
                "available to establish authenticity."
            )

        primary = max(
            signals,

            key=lambda signal: (
                AuthenticityScoringEngine
                ._severity_rank(
                    signal.severity
                ),

                signal.score,
            ),
        )

        if primary.reason:
            return primary.reason

        if primary.message:
            return primary.message

        return (
            "Authenticity evidence requires "
            "further evaluation."
        )

    # ========================================================
    # SUMMARY
    # ========================================================

    @staticmethod
    def _summary(
        decision: AuthenticityDecision,
    ) -> str:
        """
        Generate a concise machine/user-facing summary.
        """

        mapping = {
            AuthenticityDecision.VERIFIED:
                "ITR authenticity was verified.",

            AuthenticityDecision.LIKELY_AUTHENTIC:
                "No significant authenticity anomaly "
                "was detected.",

            AuthenticityDecision.MANUAL_REVIEW:
                "Authenticity evidence requires "
                "manual review.",

            AuthenticityDecision.HIGH_RISK:
                "Strong authenticity anomalies "
                "were detected.",

            AuthenticityDecision.REJECT:
                "Critical authenticity evidence "
                "was detected.",

            AuthenticityDecision.UNVERIFIED:
                "The ITR could not be independently "
                "verified.",
        }

        return mapping[
            decision
        ]

    # ========================================================
    # CONFIDENCE
    # ========================================================

    @staticmethod
    def _confidence(
        signals: tuple[
            EvidenceSignal,
            ...
        ],
        risk_level: AuthenticityRiskLevel,
        decision: AuthenticityDecision,
    ) -> float:
        """
        Estimate confidence in the evidence classification.

        This is confidence in the RULE-BASED ASSESSMENT,
        not proof that the document is genuine.
        """

        if (
            decision
            == AuthenticityDecision.REJECT
        ):
            return 0.95

        if (
            risk_level
            == AuthenticityRiskLevel.HIGH
        ):
            return 0.90

        if (
            risk_level
            == AuthenticityRiskLevel.MEDIUM
        ):
            return 0.75

        if (
            risk_level
            == AuthenticityRiskLevel.LOW
        ):
            return 0.60

        return 0.55

    # ========================================================
    # SEVERITY RANK
    # ========================================================

    @staticmethod
    def _severity_rank(
        severity: EvidenceSeverity,
    ) -> int:
        """
        Convert severity to deterministic ranking.
        """

        return {
            EvidenceSeverity.INFO: 0,

            EvidenceSeverity.LOW: 1,

            EvidenceSeverity.MEDIUM: 2,

            EvidenceSeverity.HIGH: 3,

            EvidenceSeverity.CRITICAL: 4,
        }[
            severity
        ]


# ============================================================
# CONVENIENCE FUNCTION
# ============================================================


def score_authenticity(
    evidence: AuthenticityEvidenceInput,
) -> AuthenticityScoringResult:
    """
    Convenience wrapper around AuthenticityScoringEngine.
    """

    return (
        AuthenticityScoringEngine().analyze(
            evidence
        )
    )